name: Traveler
options:
  bundleIdPrefix: com.gauthierbaron
targets:
  Traveler:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - "project.yml"
          - "Info.plist"
    info:
      path: Info.plist
    settings:
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      SWIFT_VERSION: "5.9"
